let str1 = 'Laurence';
console.log(str1, typeof str1);
let str2 = "Svekis";
console.log(str2, typeof str2);
let val1 = undefined;
console.log(val1, typeof val1);
let val2 = null;
console.log(val2, typeof val2);
let myNum = 1000;
console.log(myNum, typeof myNum);